services:
  mailer:
    build: .
    container_name: mailer
    ports:
      - "3322:3322"
    networks:
      - mailer_net
    restart: unless-stopped
    env_file:
      - .env

networks:
  mailer_net:
    external: true
