services:
  mailer:
    build: .
    container_name: mailer
    # Eliminar mapeo a host para que solo servicios en mailer_net puedan acceder
    expose:
      - "3322"
    networks:
      - mailer_net
    restart: unless-stopped
    env_file:
      - .env

networks:
  mailer_net:
    external: true